"""Report Generator Module"""

from datetime import datetime
from typing import Optional
from jinja2 import Template

REPORT_TEMPLATE = """# AI-Powered RCA Report

**Test:** {{ test_name }}  
**Run ID:** {{ run_id }}  
**Generated:** {{ generated_at }}  
**Provider:** {{ provider }}  

---

## 📋 Overview

**Failure Category:** {{ failure_category }}  
**Priority:** {{ priority }} | **Severity:** {{ severity }}  
**Confidence:** {{ confidence }}  
**Responsible Module:** {{ responsible_module }}  

**Summary:**
{{ summary }}

---

## 🔍 Deep Dive

### Root Cause
{{ root_cause }}

### Possible Reason
{{ possible_reason }}

### Business/Technical Impact
{{ impact }}

---

## 📦 Affected Modules

{% for module in modules %}
- `{{ module }}`
{% else %}
- None identified
{% endfor %}

---

## 💡 Suggested Fix

{% if suggested_fix is string %}
```python
{{ suggested_fix }}
```
{% else %}
{% for fix in suggested_fix %}
- {{ fix }}
{% endfor %}
{% endif %}

---

## 📊 Evidence Highlights

| Type | Key Finding |
|------|-------------|
{% for key, value in evidence_highlights.items() %}
| {{ key }} | {{ value }} |
{% endfor %}

---

*Report generated by AI-Powered Mobile Automation Platform*
"""


class ReportGenerator:
    """Generate reports from RCA analysis"""

    def __init__(self, output_dir: str = "./reports"):
        self.output_dir = output_dir

    def generate_markdown(self, rca_data: dict, run_id: str, test_name: str, evidence_data: dict = None) -> str:
        """Generate markdown report from RCA JSON"""
        template = Template(REPORT_TEMPLATE)

        report = template.render(
            run_id=run_id,
            test_name=test_name,
            generated_at=datetime.utcnow().isoformat(),
            provider=rca_data.get("provider", rca_data.get("llm_provider", "unknown")),
            confidence=f"{rca_data.get('confidence', 0):.0%}",
            failure_category=rca_data.get("failure_category", "Unknown"),
            priority=rca_data.get("priority", "Unknown"),
            severity=rca_data.get("severity", "Unknown"),
            responsible_module=rca_data.get("responsible_module", "Unknown"),
            summary=rca_data.get("summary", "No summary available"),
            root_cause=rca_data.get("root_cause", "Unknown"),
            possible_reason=rca_data.get("possible_reason", "Unknown"),
            impact=rca_data.get("impact", "Unknown"),
            modules=rca_data.get("affected_modules", []),
            suggested_fix=rca_data.get("suggested_fix", "No fix suggested"),
            evidence_highlights=self._extract_highlights(evidence_data or rca_data),
        )

        return report

    def _extract_highlights(self, evidence_data: dict) -> dict:
        """Extract key evidence highlights for report"""
        highlights = {}

        if "git_diff" in evidence_data and evidence_data["git_diff"]:
            diff_lines = evidence_data["git_diff"].count("\\n") + 1
            highlights["Git Changes"] = f"{diff_lines} lines modified"
            
        if "git_commit" in evidence_data and evidence_data["git_commit"]:
            highlights["Commit"] = evidence_data["git_commit"][:7]

        if "appium_logs" in evidence_data and isinstance(evidence_data["appium_logs"], list):
            error_count = sum(1 for log in evidence_data["appium_logs"] if "error" in str(log.get("message", "")).lower())
            highlights["Appium Errors"] = f"{error_count} error entries"

        if "device_logs" in evidence_data and evidence_data["device_logs"]:
            highlights["Device Logs"] = "Available"

        if "screenshot_path" in evidence_data and evidence_data["screenshot_path"]:
            highlights["Screenshot"] = "Captured"

        return highlights

    def save_report(self, content: str, run_id: str, format: str = "md") -> str:
        """Save report to file"""
        import os

        os.makedirs(self.output_dir, exist_ok=True)
        path = os.path.join(self.output_dir, f"{run_id}.{format}")

        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

        return path

    def generate_html(self, markdown_content: str) -> str:
        """Convert markdown to HTML"""
        import markdown

        html_body = markdown.markdown(markdown_content, extensions=['tables'])
        
        # Wrap in a nice HTML structure
        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>RCA Report</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1, h2, h3 {{ color: #2c3e50; border-bottom: 1px solid #eee; padding-bottom: 5px; }}
        code {{ background: #f4f4f4; border-radius: 4px; padding: 2px 4px; font-family: ui-monospace, SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace; }}
        pre {{ background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }}
        pre code {{ background: none; padding: 0; }}
        table {{ border-collapse: collapse; width: 100%; margin-bottom: 20px; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #f2f2f2; }}
    </style>
</head>
<body>
    {html_body}
</body>
</html>
"""

    def generate_pdf(self, html_content: str, output_path: str) -> Optional[str]:
        """Generate PDF from HTML"""
        # Placeholder for PDF generation
        return None