"""A path containing a space breaks React Native 0.68's own build tooling.

Three separate failures on one machine, all from "automation bot":

    sed:  /Users/Aritro/Desktop/automation: No such file or directory
    find: /Users/Aritro/Desktop/automation: No such file or directory
    /bin/sh: /Users/Aritro/Desktop/automation: No such file or directory
        Command PhaseScriptExecution failed (target 'FBReactNativeSpec')

RN shells out with unquoted paths, so the space truncates them and the command
runs against a directory that does not exist. Its RCT-Folly patch, the
Podfile's post_install and FBReactNativeSpec's codegen phase all fail this way,
and every resulting error names a dependency rather than the directory.

The platform repairs the first two afterwards. It cannot repair the third:
that script is generated by RN and executed by Xcode. So the condition is
reported before the build rather than discovered inside it.
"""
import pytest

from automation.projects.builder import app_builder


def test_01_a_clean_path_is_silent():
    assert app_builder.path_has_space(
        "/Users/dev/Desktop/AutomationTesting/repos/abc") is None


def test_02_the_reported_path_is_caught():
    msg = app_builder.path_has_space("/Users/Aritro/Desktop/automation bot/repos/x")
    assert msg is not None


def test_03_the_offending_component_is_named():
    """Naming the whole path is not actionable; naming the folder is."""
    msg = app_builder.path_has_space("/Users/Aritro/Desktop/automation bot/repos/x")
    assert "'automation bot'" in msg


def test_04_a_fix_is_suggested():
    msg = app_builder.path_has_space("/Users/Aritro/Desktop/automation bot/repos/x")
    assert "automation-bot" in msg, "must suggest the hyphenated name"


def test_05_it_says_why_the_platform_cannot_just_repair_it():
    """The codegen phase is the part we do not own — that must be explicit, or
    the next person assumes the platform is simply not trying."""
    msg = app_builder.path_has_space("/Users/x/my project/repos/y")
    assert "codegen" in msg.lower() and "Xcode" in msg


@pytest.mark.parametrize("path", [
    "/Users/x/two words/repos/y",
    "/Users/x/repos/a b",
    "/Volumes/My Drive/platform/repos/z",
])
def test_06_a_space_anywhere_above_the_checkout_counts(path):
    assert app_builder.path_has_space(path) is not None


def test_07_the_ios_build_checks_before_doing_work():
    """Structural: the check must come before pod install, not after."""
    import inspect
    src = inspect.getsource(app_builder.build_ios)
    assert "path_has_space" in src, "the iOS build does not check the path"
    assert src.index("path_has_space") < src.index("_pod_install"), \
        "the check runs after CocoaPods — too late to save the wait"
