"""Phase 4G.1 — Alembic can build the complete schema from scratch.

Before this, `alembic upgrade head` produced 4 tables while the models declared
24, and the live database was *stamped* at that 4-table revision — so Alembic
reported success while 20 tables were missing. A PostgreSQL cutover driven by
that stamp would have silently produced an unusable database.

These tests build a real database with Alembic and diff it against
Base.metadata. `alembic upgrade head` exiting 0 proves nothing on its own — the
autogenerated migration originally crashed *after* committing most tables, and
still reported success at the shell.
"""
import os
import subprocess
import sys

import pytest
from sqlalchemy import create_engine, inspect

from automation.database.config import Base
from automation.database import models  # noqa: F401 — populates the metadata

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OLD_HEAD = "778d43e546f3"      # the 4-table revision production is stamped at


def _alembic(args, db_path):
    env = {**os.environ, "DATABASE_URL": f"sqlite:///{db_path}", "PYTHONPATH": REPO}
    return subprocess.run([sys.executable, "-m", "alembic", *args],
                          cwd=REPO, env=env, capture_output=True, text=True, timeout=300)


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    """A database built ONLY by `alembic upgrade head`."""
    db = tmp_path_factory.mktemp("alembic") / "head.db"
    res = _alembic(["upgrade", "head"], db)
    assert res.returncode == 0, f"upgrade failed:\n{res.stderr[-3000:]}"
    # The original defect: a crash inside batch mode after tables were committed.
    assert "Traceback" not in res.stderr, f"upgrade raised:\n{res.stderr[-3000:]}"
    return inspect(create_engine(f"sqlite:///{db}"))


def _model_tables():
    return {t.name for t in Base.metadata.sorted_tables}


# ── fresh database ──────────────────────────────────────────────────────────

def test_01_a_fresh_upgrade_creates_every_model_table(built):
    live = set(built.get_table_names()) - {"alembic_version"}
    assert live == _model_tables(), (
        f"missing={sorted(_model_tables() - live)} extra={sorted(live - _model_tables())}")
    assert len(live) == 24


def test_02_every_column_exists_with_matching_nullability(built):
    problems = []
    for t in Base.metadata.sorted_tables:
        got = {c["name"]: c for c in built.get_columns(t.name)}
        for c in t.columns:
            if c.name not in got:
                problems.append(f"{t.name}.{c.name} MISSING")
            elif c.nullable != got[c.name]["nullable"]:
                problems.append(f"{t.name}.{c.name} nullable={got[c.name]['nullable']} want {c.nullable}")
    assert not problems, problems


def test_03_every_index_exists(built):
    missing = []
    for t in Base.metadata.sorted_tables:
        got = {i["name"] for i in built.get_indexes(t.name)}
        missing += [f"{t.name}.{ix.name}" for ix in t.indexes if ix.name not in got]
    assert not missing, missing


def test_04_every_unique_constraint_exists(built):
    """The constraint class _add_missing_columns() can never create."""
    missing = []
    for t in Base.metadata.sorted_tables:
        got = {tuple(sorted(u["column_names"])) for u in built.get_unique_constraints(t.name)}
        got |= {tuple(sorted(i["column_names"])) for i in built.get_indexes(t.name) if i.get("unique")}
        for con in t.constraints:
            if con.__class__.__name__ == "UniqueConstraint":
                want = tuple(sorted(c.name for c in con.columns))
                if want not in got:
                    missing.append(f"{t.name}{want}")
        for c in t.columns:
            if c.unique and (c.name,) not in got:
                missing.append(f"{t.name}.{c.name}")
    assert not missing, missing
    # the multi-column one this platform actually depends on
    devices = {tuple(sorted(u["column_names"])) for u in built.get_unique_constraints("devices")}
    assert ("machine_id", "udid") in devices


def test_05_every_foreign_key_exists(built):
    missing = []
    for t in Base.metadata.sorted_tables:
        got = {(tuple(f["constrained_columns"]), f["referred_table"])
               for f in built.get_foreign_keys(t.name)}
        for fk in t.foreign_key_constraints:
            want = (tuple(c.name for c in fk.columns), fk.referred_table.name)
            if want not in got:
                missing.append(f"{t.name}{want}")
    assert not missing, missing


def test_06_primary_keys_match(built):
    bad = []
    for t in Base.metadata.sorted_tables:
        got = tuple(built.get_pk_constraint(t.name)["constrained_columns"])
        want = tuple(c.name for c in t.primary_key)
        if got != want:
            bad.append(f"{t.name}: {got} != {want}")
    assert not bad, bad


# ── false-stamp protection ──────────────────────────────────────────────────

def test_07_the_old_revision_alone_is_not_the_schema(tmp_path):
    """Head must be strictly beyond the 4-table revision production is stamped at."""
    db = tmp_path / "old.db"
    res = _alembic(["upgrade", OLD_HEAD], db)
    assert res.returncode == 0, res.stderr[-2000:]
    live = set(inspect(create_engine(f"sqlite:///{db}")).get_table_names()) - {"alembic_version"}
    assert len(live) == 4, f"the old revision should still be 4 tables, got {sorted(live)}"
    assert len(_model_tables()) == 24
    assert live < _model_tables(), "the old revision must be a strict subset of the models"


def test_08_head_is_not_the_old_revision():
    res = subprocess.run([sys.executable, "-m", "alembic", "heads"],
                         cwd=REPO, env={**os.environ, "PYTHONPATH": REPO},
                         capture_output=True, text=True, timeout=120)
    assert res.returncode == 0, res.stderr[-2000:]
    assert OLD_HEAD not in res.stdout, "head is still the 4-table revision"


def test_09_there_is_exactly_one_head():
    """Branched heads would make `upgrade head` ambiguous."""
    res = subprocess.run([sys.executable, "-m", "alembic", "heads"],
                         cwd=REPO, env={**os.environ, "PYTHONPATH": REPO},
                         capture_output=True, text=True, timeout=120)
    heads = [l for l in res.stdout.splitlines() if l.strip() and "head" in l]
    assert len(heads) == 1, f"expected one head, got {heads}"


# ── no drift between migrations and models ──────────────────────────────────

def test_10_autogenerate_detects_no_drift(tmp_path):
    """`alembic check` is the guard that keeps this from rotting."""
    db = tmp_path / "drift.db"
    assert _alembic(["upgrade", "head"], db).returncode == 0
    res = _alembic(["check"], db)
    assert res.returncode == 0, (
        "models and migrations have drifted — add a revision:\n"
        + (res.stdout + res.stderr)[-3000:])
    assert "No new upgrade operations detected" in (res.stdout + res.stderr)


# ── env wiring ──────────────────────────────────────────────────────────────

def test_11_env_honours_database_url(tmp_path):
    """Without this the migration runs against alembic.ini's hardcoded file."""
    db = tmp_path / "explicit.db"
    assert _alembic(["upgrade", "head"], db).returncode == 0
    assert db.exists(), "DATABASE_URL was ignored — alembic wrote somewhere else"


def test_12_the_repo_default_sqlite_file_was_not_written(tmp_path):
    from pathlib import Path
    stale = Path(REPO) / "test_automation_new.db"
    before = stale.stat().st_mtime if stale.exists() else None
    db = tmp_path / "isolated.db"
    assert _alembic(["upgrade", "head"], db).returncode == 0
    after = stale.stat().st_mtime if stale.exists() else None
    assert before == after, "a migration touched the repo-root SQLite file"


# ── _add_missing_columns() keeps its (now narrower) role ────────────────────

def test_13_add_missing_columns_still_exists_and_is_column_only():
    """Retained deliberately: it is the only thing that repairs an existing
    SQLite deployment that was never stamped. It can add columns and nothing
    else — which is exactly why Alembic had to become authoritative."""
    import inspect as _i
    from automation.database import config
    assert callable(config._add_missing_columns)
    src = _i.getsource(config._add_missing_columns)
    assert "ADD COLUMN" in src
    for forbidden in ("CREATE INDEX", "ADD CONSTRAINT", "DROP", "CREATE UNIQUE"):
        assert forbidden not in src, f"_add_missing_columns now emits {forbidden}"


def test_14_initialize_database_is_unchanged_for_existing_deployments():
    import inspect as _i
    from automation.database import config
    src = _i.getsource(config.initialize_database)
    assert "create_all" in src and "_add_missing_columns" in src, \
        "4G.1 must not change runtime schema creation — that is a later phase"
