"""Initial migration

Revision ID: 778d43e546f3
Revises: 
Create Date: 2026-06-30 17:57:17.130146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778d43e546f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_suite', sa.String(length=255), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('build_number', sa.String(length=50), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('commit_sha', sa.String(length=255), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('flaky_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('evidence_bundles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('git_commit', sa.String(length=255), nullable=True),
    sa.Column('git_author', sa.String(length=255), nullable=True),
    sa.Column('git_branch', sa.String(length=255), nullable=True),
    sa.Column('git_diff', sa.Text(), nullable=True),
    sa.Column('changed_files', sa.Text(), nullable=True),
    sa.Column('appium_logs', sa.Text(), nullable=True),
    sa.Column('device_logs', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=1024), nullable=True),
    sa.Column('video_path', sa.String(length=1024), nullable=True),
    sa.Column('xml_page_source', sa.Text(), nullable=True),
    sa.Column('network_logs', sa.Text(), nullable=True),
    sa.Column('failed_locator', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('rca_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('failure_category', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('possible_reason', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('responsible_module', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(length=100), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rca_reports')
    op.drop_table('evidence_bundles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('test_runs')
    # ### end Alembic commands ###
