"""complete schema baseline

Revision ID: 84af52af343c
Revises: 778d43e546f3
Create Date: 2026-09-05 10:42:38.928146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '84af52af343c'
down_revision: Union[str, Sequence[str], None] = '778d43e546f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('android_bot_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('cross_app_flow_edits',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('based_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=120), nullable=False),
    sa.Column('udid', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('platform_version', sa.String(length=50), nullable=True),
    sa.Column('connection_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('reserved_by', sa.String(length=36), nullable=True),
    sa.Column('reserved_at', sa.DateTime(), nullable=True),
    sa.Column('reserved_state', sa.String(length=20), nullable=True),
    sa.Column('wda_port', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'udid', name='uq_devices_machine_udid')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_reserved_by'), ['reserved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_udid'), ['udid'], unique=False)

    op.create_table('execution_agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('os', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('connected_devices', sa.JSON(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('restart_count', sa.Integer(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('is_draining', sa.Boolean(), nullable=True),
    sa.Column('is_backend', sa.Boolean(), nullable=True),
    sa.Column('agent_credential_hash', sa.String(length=64), nullable=True),
    sa.Column('agent_credential_issued_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_agents_agent_credential_hash'), ['agent_credential_hash'], unique=False)

    op.create_table('module_stability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.String(), nullable=True),
    sa.Column('pass_count', sa.Integer(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('flaky_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('module_stability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_stability_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_stability_module_name'), ['module_name'], unique=False)

    op.create_table('system_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('actual_fix', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_feedback_id'), ['id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('dependency_graphs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('graph_data', sa.JSON(), nullable=True),
    sa.Column('api_endpoints', sa.JSON(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['application_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('git_url', sa.String(length=1024), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('repo_type', sa.String(length=50), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('clone_status', sa.String(length=50), nullable=True),
    sa.Column('clone_error', sa.Text(), nullable=True),
    sa.Column('current_branch', sa.String(length=255), nullable=True),
    sa.Column('last_pull_at', sa.DateTime(), nullable=True),
    sa.Column('last_execution_at', sa.DateTime(), nullable=True),
    sa.Column('app_path', sa.String(length=1024), nullable=True),
    sa.Column('app_bundle_id', sa.String(length=255), nullable=True),
    sa.Column('build_status', sa.String(length=50), nullable=True),
    sa.Column('build_error', sa.Text(), nullable=True),
    sa.Column('last_build_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['application_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('jira_url', sa.String(length=255), nullable=True),
    sa.Column('jira_token', sa.String(length=255), nullable=True),
    sa.Column('github_repo', sa.String(length=255), nullable=True),
    sa.Column('github_token', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['test_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('saved_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('bundle_id', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('covers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['test_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_scenarios_project_id'), ['project_id'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('pr_number', sa.String(length=50), nullable=True),
    sa.Column('pr_url', sa.String(length=500), nullable=True),
    sa.Column('match_key', sa.String(length=120), nullable=True),
    sa.Column('scenario_ids', sa.JSON(), nullable=True),
    sa.Column('setup_scenario_id', sa.String(length=36), nullable=True),
    sa.Column('ticket_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_run_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['test_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_match_key'), ['match_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_pr_number'), ['pr_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_project_id'), ['project_id'], unique=False)

    op.create_table('ai_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['test_projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_mb', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('network_requests', sa.Integer(), nullable=True),
    sa.Column('avg_response_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('app_launch_time_s', sa.Float(), nullable=True),
    sa.Column('avg_cpu_percent', sa.Float(), nullable=True),
    sa.Column('peak_cpu_percent', sa.Float(), nullable=True),
    sa.Column('avg_memory_mb', sa.Float(), nullable=True),
    sa.Column('peak_memory_mb', sa.Float(), nullable=True),
    sa.Column('avg_fps', sa.Float(), nullable=True),
    sa.Column('min_fps', sa.Float(), nullable=True),
    sa.Column('dropped_frames', sa.Integer(), nullable=True),
    sa.Column('api_calls', sa.Integer(), nullable=True),
    sa.Column('avg_api_response_ms', sa.Float(), nullable=True),
    sa.Column('slowest_api_ms', sa.Float(), nullable=True),
    sa.Column('slowest_api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=1), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('scenario_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('scenario_num', sa.String(length=10), nullable=True),
    sa.Column('scenario_name', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('consumer_status', sa.String(length=10), nullable=True),
    sa.Column('business_status', sa.String(length=10), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('launch_time', sa.Float(), nullable=True),
    sa.Column('screenshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual_regression_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('screen_name', sa.String(length=255), nullable=True),
    sa.Column('diff_percentage', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('baseline_path', sa.String(length=500), nullable=True),
    sa.Column('current_path', sa.String(length=500), nullable=True),
    sa.Column('diff_path', sa.String(length=500), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rca_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affected_modules', sa.JSON(), nullable=True))

    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('report_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('report_generated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_flaky', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('risk_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planned_scenarios', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('flaky_detected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('visual_warning', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('crash_detected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('agent_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('machine_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('job_state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bot_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('test_suite',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('test_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('timeline',
               existing_type=sqlite.JSON(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_test_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_runs_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_runs_test_name'), ['test_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_runs_test_suite'), ['test_suite'], unique=False)
        batch_op.create_foreign_key('fk_test_runs_project_id_test_projects', 'test_projects', ['project_id'], ['id'])
        batch_op.create_foreign_key('fk_test_runs_agent_id_execution_agents', 'execution_agents', ['agent_id'], ['id'])
        batch_op.drop_column('flaky_score')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flaky_score', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint('fk_test_runs_agent_id_execution_agents', type_='foreignkey')
        batch_op.drop_constraint('fk_test_runs_project_id_test_projects', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_test_runs_test_suite'))
        batch_op.drop_index(batch_op.f('ix_test_runs_test_name'))
        batch_op.drop_index(batch_op.f('ix_test_runs_machine_id'))
        batch_op.drop_index(batch_op.f('ix_test_runs_id'))
        batch_op.alter_column('timeline',
               existing_type=sa.String(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('test_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('test_suite',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('bot_type')
        batch_op.drop_column('job_state')
        batch_op.drop_column('machine_id')
        batch_op.drop_column('agent_id')
        batch_op.drop_column('crash_detected')
        batch_op.drop_column('visual_warning')
        batch_op.drop_column('flaky_detected')
        batch_op.drop_column('attempts')
        batch_op.drop_column('planned_scenarios')
        batch_op.drop_column('risk_score')
        batch_op.drop_column('is_flaky')
        batch_op.drop_column('report_generated_at')
        batch_op.drop_column('report_summary')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('rca_reports', schema=None) as batch_op:
        batch_op.drop_column('affected_modules')

    op.drop_table('visual_regression_results')
    op.drop_table('scenario_results')
    op.drop_table('performance_summaries')
    op.drop_table('performance_metrics')
    op.drop_table('ai_recommendations')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_project_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_pr_number'))
        batch_op.drop_index(batch_op.f('ix_tickets_match_key'))

    op.drop_table('tickets')
    with op.batch_alter_table('saved_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_scenarios_project_id'))

    op.drop_table('saved_scenarios')
    op.drop_table('project_settings')
    op.drop_table('test_projects')
    op.drop_table('dependency_graphs')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_feedback_id'))

    op.drop_table('user_feedback')
    op.drop_table('system_alerts')
    with op.batch_alter_table('module_stability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_stability_module_name'))
        batch_op.drop_index(batch_op.f('ix_module_stability_id'))

    op.drop_table('module_stability')
    with op.batch_alter_table('execution_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_agents_agent_credential_hash'))

    op.drop_table('execution_agents')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_udid'))
        batch_op.drop_index(batch_op.f('ix_devices_reserved_by'))
        batch_op.drop_index(batch_op.f('ix_devices_machine_id'))
        batch_op.drop_index(batch_op.f('ix_devices_id'))

    op.drop_table('devices')
    op.drop_table('cross_app_flow_edits')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))

    op.drop_table('chat_sessions')
    op.drop_table('audit_logs')
    op.drop_table('application_groups')
    # ### end Alembic commands ###
